### ISSUE TITLE
Web - any visual bugs

### ISSUE THREAD

**Issue by maurobotta** [JordanADavies/liquid_progress_indicator#12]
Hi

I'm tring on Web, there are  any visual bugs

Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Versione 10.0.18363.1082], locale it-IT)

**Comment by n0npax** [comment]
Hi,

I believe I'm facing the same issue on:

> [✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Linux)
Dart version 2.10.0

To be clear example code produces given issue:

![image](https://user-images.githubusercontent.com/10343861/93431870-14aa9680-f908-11ea-8f03-c2f76afc20dc.png)

**Comment by JordanADavies** [comment]
Closing as this is an issue on Flutters side not this package. https://github.com/flutter/flutter/issues/64371
