### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by nilsreichardt** [JordanADavies/liquid_progress_indicator#13]
## Description
All dependencies are migrated to null safety. So we should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by 6h4n3m** [comment]
I do not think the package is maintained anymore.

I've forked and migrated the package myself since I'm using it in one of my projects, you can depend on my fork like this:

```
liquid_progress_indicator:
    git: https://github.com/6h4n3m/liquid_progress_indicator.git
```

Some changes will be required to your app/package because some parameters are now required but were not before, but it's as easy as providing some colors/widths...etc.

**Comment by JErazo7** [comment]
> I do not think the package is maintained anymore.
> 
> I've forked and migrated the package myself since I'm using it in one of my projects, you can depend on my fork like this:
> 
> ```
> liquid_progress_indicator:
>     git: https://github.com/6h4n3m/liquid_progress_indicator.git
> ```
> 
> Some changes will be required to your app/package because some parameters are now required but were not before, but it's as easy as providing some colors/widths...etc.
> 
> Edit: To clarify, I'm not planning on making any changes or maintaining the library, you're welcome to fork my own fork and use that in your production code if you're afraid any changes will be introduced into master, or you can even depend on a specific ref.

Can you upload as a new package in pub.dev?

**Comment by 6h4n3m** [comment]
> > I do not think the package is maintained anymore.
> > I've forked and migrated the package myself since I'm using it in one of my projects, you can depend on my fork like this:
> > ```
> > liquid_progress_indicator:
> >     git: https://github.com/6h4n3m/liquid_progress_indicator.git
> > ```
> > 
> > 
> > Some changes will be required to your app/package because some parameters are now required but were not before, but it's as easy as providing some colors/widths...etc.
> > Edit: To clarify, I'm not planning on making any changes or maintaining the library, you're welcome to fork my own fork and use that in your production code if you're afraid any changes will be introduced into master, or you can even depend on a specific ref.
> 
> Can you upload as a new package in pub.dev?

https://pub.dev/packages/liquid_progress_indicator_ns

**Comment by slavap** [comment]
@6h4n3m 
You have made a mistake in your null safety porting: borderWidth and borderColor are required ONLY if one of them is defined, they could be both null (and it was always working like that). Please fix it.
```dart
if (borderWidth != null && borderColor == null ||
        borderColor != null && borderWidth == null) {
      throw ArgumentError("borderWidth and borderColor should both be set.");
    }
```

**Comment by volgin** [comment]
> @6h4n3m
> You have made a mistake in your null safety porting: borderWidth and borderColor are required ONLY if one of them is defined, they could be both null (and it was always working like that). Please fix it. Check in non-null safety version was:
> 
> ```dart
> if (borderWidth != null && borderColor == null ||
>         borderColor != null && borderWidth == null) {
>       throw ArgumentError("borderWidth and borderColor should both be set.");
>     }
> ```

This code is obviously wrong.

**Comment by volgin** [comment]
@slavap Missing parenthesis. It should be:

```
if ((borderWidth != null && borderColor == null) ||
        (borderColor != null && borderWidth == null)) {
      throw ArgumentError("borderWidth and borderColor should both be set.");
}
```

**Comment by slavap** [comment]
@volgin Why? At least in non-migrated to null safety version was no need to define explicitly both borderWidth and borderColor.

**Comment by volgin** [comment]
@slavap I understand what you are saying. But the code that you posted does NOT do what you think it does. Without extra parenthesis it makes no sense.

**Comment by slavap** [comment]
@volgin What parenthesis are you talking about? This code works and checks that both are null OR both are not null.

**Comment by JordanADavies** [comment]
Done. Sorry it's taken so long.
