### ISSUE TITLE
ShapePath for LiquidCustomProgressIndicator

### ISSUE THREAD

**Issue by fujoos** [JordanADavies/liquid_progress_indicator#3]
Thanks for the  wonderful plugin. I tried using a relative canvas context dimension for its shapepath but it does not work. Pls what am i doing wrong? i.e. 
  Path _battery(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    return Path()
      ..moveTo(size.width / 3.1, size.height / 1.25)
      ..lineTo(size.width / 1.48, size.height / 1.25)
      ..lineTo(size.width / 1.48, size.height / 4.27)
      ..lineTo(size.width / 1.78, size.height / 4.27)
      ..lineTo(size.width / 1.78, size.height / 5.12)
      ..lineTo(size.width / 2.0, size.height / 5.12)
      ..lineTo(size.width / 2.27, size.height / 5.12)
      ..lineTo(size.width / 2.27, size.height / 4.27)
      ..lineTo(size.width / 3.1, size.height / 4.27)
      //..lineTo(size.width / 3.1, size.height / 1.25)
      ..close();
  }

**Comment by JordanADavies** [comment]
Thanks for using it!

This should be fixed in v0.3.2.
