### ISSUE TITLE
Error: Could not resolve the package 'liquid_progress_indicator' in 'package:liquid_progress_indicator/liquid_progress_indicator.dart'

### ISSUE THREAD

**Issue by mrhuseyinahmet** [JordanADavies/liquid_progress_indicator#9]
When importing the file and trying to run the application I am getting this error:
Compiler message:
Error: Could not resolve the package 'liquid_progress_indicator' in 'package:liquid_progress_indicator/liquid_progress_indicator.dart'.
lib/UI/Pages/GymSubPages/ExerciseListPage.dart:8:8: Error: Not found: 'package:liquid_progress_indicator/liquid_progress_indicator.dart'
import 'package:liquid_progress_indicator/liquid_progress_indicator.dart';

**Comment by AlexHartford** [comment]
You have to stop and start your app when installing new packages.

**Comment by JordanADavies** [comment]
Closing as looks like an issue with project configuration.
